\connect dataprocessing

GRANT ALL PRIVILEGES ON DATABASE dataprocessing TO devuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO devuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO devuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO devuser;