listen_addresses = '*'
max_connections = 100

shared_buffers = 128MB
work_mem = 4MB

log_destination = 'stderr'
logging_collector = off
log_statement = 'all'
log_duration = on
log_min_duration_statement = 0
log_line_prefix = '%t [%p] %u@%d '

timezone = 'UTC'